name: wait-then-echo
on:
  workflow_dispatch:
    inputs:
      dispatch_id:
        description: An ID used to identify the workflow run
        required: true
        type: string
      wait_time:
        description: Time to wait before echoing
        required: true
        type: number
      message:
        description: Message to echo after waiting
        required: true
        type: string
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch ${{ inputs.dispatch_id }}
        run: echo "Dispatch ${{ inputs.dispatch_id }}"
  wait-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep ${{ inputs.wait_time }}
      - name: Echo
        run: echo "${{ inputs.message }}"
